import Navbar from './components/Navbar'
import Hero from './components/Hero'
import Reveal from './components/Reveal'
import ProjectShowcase from './components/ProjectShowcase'
import { experience, education, projects, skills } from './data/portfolio'

const headers = { work: ['01', 'Selected Work'], about: ['02', 'About'], experience: ['03', 'Experience / Leadership'], education: ['04', 'Education'], skills: ['05', 'Skills'] }
function SectionHeading({ id }) { const [number, title] = headers[id]; return <Reveal className="section-heading"><span className="section-number">{number}</span><h2>{title}</h2></Reveal> }

export default function App() {
  return <><a className="skip-link" href="#work">Skip to selected work</a><Navbar /><main><Hero />
    <section id="work" className="section section--work" aria-labelledby="work-title"><div className="container"><SectionHeading id="work" /><p className="section-intro" id="work-title">A focused selection of full-stack and systems work, with room to grow as I build more.</p><div className="project-list">{projects.map((project, index) => <ProjectShowcase key={project.title} project={project} index={index} />)}</div></div></section>
    <section id="about" className="section section--about" aria-labelledby="about-title"><div className="container about-layout"><div><SectionHeading id="about" /><div className="about-copy" id="about-title"><Reveal><p>I’m Giovanni Peila, a Computer Science student at Cal Poly San Luis Obispo with interests in software engineering, artificial intelligence and machine learning, and systems.</p></Reveal><Reveal delay={0.08}><p>I started programming and building websites at a young age—the original version of this portfolio was one of those early projects. Since then, my work has grown from small programming exercises into full-stack applications and systems-focused projects.</p></Reveal><Reveal delay={0.16}><p>I’m especially interested in building reliable software, understanding how systems communicate, and exploring technology across finance, privacy, and security.</p></Reveal></div></div><Reveal className="progression-frame" delay={0.12}><div className="progression-glass" aria-label="Portfolio progression preview"><div className="progression-stage"><span className="mono-label">EARLY WEB WORK</span><span className="progression-year">13</span></div><div className="progression-line" aria-hidden="true"><span /></div><div className="progression-stage progression-stage--current"><span className="mono-label">CURRENT WORK</span><span className="progression-year">NOW</span></div></div><p className="progression-note">A reserved stage for the future early-portfolio → current-work scroll sequence.</p></Reveal></div></section>
    <section id="experience" className="section section--experience" aria-labelledby="experience-title"><div className="container"><SectionHeading id="experience" /><div className="timeline" id="experience-title">{experience.map((item, index) => <Reveal className="timeline-item" key={`${item.organization}-${item.role}`} delay={index * 0.05}><div className="timeline-marker" aria-hidden="true" /><div className="timeline-meta">{item.date}</div><div className="timeline-content"><h3>{item.role}</h3><p className="timeline-organization">{item.organization}{item.location ? ` · ${item.location}` : ''}</p><p>{item.description}</p></div></Reveal>)}</div></div></section>
    <section id="education" className="section section--education" aria-labelledby="education-title"><div className="container"><SectionHeading id="education" /><div className="education-grid" id="education-title"><div className="education-list">{education.map((item, index) => <Reveal className="education-item" key={item.school} delay={index * 0.06}><span className="mono-label">{item.date}</span><h3>{item.school}</h3><p className="education-program">{item.program}</p>{item.detail && <p>{item.detail}</p>}{item.gpa && <p className="education-gpa">{item.gpa}</p>}</Reveal>)}</div><Reveal className="coursework" delay={0.14}><span className="mono-label">SELECTED PREVIOUS COURSEWORK</span><ul><li>Database &amp; SQL — CIT 180</li><li>Intro to Java — CIT 130</li><li>Advanced Java — CIT 230</li><li>AP Computer Science A</li><li>Systems Analysis &amp; Design — CIT 260</li><li>Computer Science II — CS 202</li><li>Intro to Programming — CIT 129</li></ul></Reveal></div></div></section>
    <section id="skills" className="section section--skills" aria-labelledby="skills-title"><div className="container"><SectionHeading id="skills" /><p className="section-intro section-intro--narrow" id="skills-title">Hands-on technologies and concepts grouped by the work they support—not proficiency percentages.</p><div className="skills-grid">{skills.map((group, index) => <Reveal className="skill-group" key={group.label} delay={index * 0.05}><h3>{group.label}</h3><p>{group.items.join(' · ')}</p></Reveal>)}</div></div></section>
    <section id="contact" className="section section--contact" aria-labelledby="contact-title"><div className="container"><Reveal className="contact-surface"><span className="section-number">06</span><h2 id="contact-title">Let’s connect.</h2><p>I’m always interested in connecting with people working in software, AI/ML, systems, and related technical areas.</p><a className="contact-email" href="mailto:giovannipeila67@gmail.com">giovannipeila67@gmail.com</a><div className="contact-links" aria-label="Professional links"><a href="https://github.com/Giovanni-67" target="_blank" rel="noreferrer">GitHub <span aria-hidden="true">↗</span></a><a href="https://linkedin.com/in/giovanni-p-60a9973a5" target="_blank" rel="noreferrer">LinkedIn <span aria-hidden="true">↗</span></a></div></Reveal></div></section>
  </main></>
}
